FROM travelping/scapy
RUN python3 -m pip install IPy
ADD pkt_generator.py /pkt_generator.py
ADD LLDP_TLV.py /LLDP_TLV.py
ADD NotificationBox.py /NotificationBox.py
ADD Packet_Generator.py /Packet_Generator.py
ADD tool.py /tool.py
ADD openflow.pcapng /openflow.pcapng