version: "3"
services:
  compose_pkt_generator_producer:
    #lui ha l'interprete
    build: ../pkt_generator_develop
    command: tail -F anything
    cap_add:
      - NET_ADMIN
    depends_on:
      - compose_pkt_generator_monitor
    networks:
      pkt_net:
        ipv4_address: 192.168.238.5

  compose_pkt_generator_monitor:
    build: ../pkt_generator_develop
    command: python3 pkt_generator.py -m
    cap_add:
      - NET_ADMIN
    networks:
      pkt_net:
        ipv4_address: 192.168.238.4

networks:
  pkt_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.238.0/24"